// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using budget_back.Infrastructure;

#nullable disable

namespace budget_back.Infrastructure.Migrations
{
    [DbContext(typeof(BudgetDbContext))]
    [Migration("20260817074429_AddUsersAndManagerToFamilyAndBuilding")]
    partial class AddUsersAndManagerToFamilyAndBuilding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("BuildingUser", b =>
                {
                    b.Property<int>("BuildingsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsersId")
                        .HasColumnType("INTEGER");

                    b.HasKey("BuildingsId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("BuildingUsers", (string)null);
                });

            modelBuilder.Entity("FamilyUser", b =>
                {
                    b.Property<int>("FamiliesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsersId")
                        .HasColumnType("INTEGER");

                    b.HasKey("FamiliesId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("FamilyUsers", (string)null);
                });

            modelBuilder.Entity("TravelUser", b =>
                {
                    b.Property<int>("TravelsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsersId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TravelsId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("TravelUsers", (string)null);
                });

            modelBuilder.Entity("budget_back.Domain.AggregatedModels.Building", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("ExpenseScopeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ManagerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExpenseScopeId")
                        .IsUnique();

                    b.HasIndex("ManagerId");

                    b.ToTable("Buildings", (string)null);
                });

            modelBuilder.Entity("budget_back.Domain.AggregatedModels.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryCreationType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("ExpenseScopeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExpenseScopeId")
                        .IsUnique();

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("budget_back.Domain.AggregatedModels.Expence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("ExpenseScopeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExpenseScopeId");

                    b.ToTable("Expences", (string)null);
                });

            modelBuilder.Entity("budget_back.Domain.AggregatedModels.ExpenseScope", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ExpenseScopes", (string)null);
                });

            modelBuilder.Entity("budget_back.Domain.AggregatedModels.Family", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("ExpenseScopeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ManagerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExpenseScopeId")
                        .IsUnique();

                    b.HasIndex("ManagerId");

                    b.ToTable("Families", (string)null);
                });

            modelBuilder.Entity("budget_back.Domain.AggregatedModels.Travel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExpenseScopeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExpenseScopeId")
                        .IsUnique();

                    b.ToTable("Travels", (string)null);
                });

            modelBuilder.Entity("budget_back.Domain.AggregatedModels.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("BuildingUser", b =>
                {
                    b.HasOne("budget_back.Domain.AggregatedModels.Building", null)
                        .WithMany()
                        .HasForeignKey("BuildingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("budget_back.Domain.AggregatedModels.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FamilyUser", b =>
                {
                    b.HasOne("budget_back.Domain.AggregatedModels.Family", null)
                        .WithMany()
                        .HasForeignKey("FamiliesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("budget_back.Domain.AggregatedModels.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelUser", b =>
                {
                    b.HasOne("budget_back.Domain.AggregatedModels.Travel", null)
                        .WithMany()
                        .HasForeignKey("TravelsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("budget_back.Domain.AggregatedModels.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("budget_back.Domain.AggregatedModels.Building", b =>
                {
                    b.HasOne("budget_back.Domain.AggregatedModels.ExpenseScope", "ExpenseScope")
                        .WithOne()
                        .HasForeignKey("budget_back.Domain.AggregatedModels.Building", "ExpenseScopeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("budget_back.Domain.AggregatedModels.User", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ExpenseScope");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("budget_back.Domain.AggregatedModels.Category", b =>
                {
                    b.HasOne("budget_back.Domain.AggregatedModels.ExpenseScope", "ExpenseScope")
                        .WithOne()
                        .HasForeignKey("budget_back.Domain.AggregatedModels.Category", "ExpenseScopeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExpenseScope");
                });

            modelBuilder.Entity("budget_back.Domain.AggregatedModels.Expence", b =>
                {
                    b.HasOne("budget_back.Domain.AggregatedModels.ExpenseScope", "ExpenseScope")
                        .WithMany("Expences")
                        .HasForeignKey("ExpenseScopeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExpenseScope");
                });

            modelBuilder.Entity("budget_back.Domain.AggregatedModels.Family", b =>
                {
                    b.HasOne("budget_back.Domain.AggregatedModels.ExpenseScope", "ExpenseScope")
                        .WithOne()
                        .HasForeignKey("budget_back.Domain.AggregatedModels.Family", "ExpenseScopeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("budget_back.Domain.AggregatedModels.User", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ExpenseScope");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("budget_back.Domain.AggregatedModels.Travel", b =>
                {
                    b.HasOne("budget_back.Domain.AggregatedModels.ExpenseScope", "ExpenseScope")
                        .WithOne()
                        .HasForeignKey("budget_back.Domain.AggregatedModels.Travel", "ExpenseScopeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExpenseScope");
                });

            modelBuilder.Entity("budget_back.Domain.AggregatedModels.ExpenseScope", b =>
                {
                    b.Navigation("Expences");
                });
#pragma warning restore 612, 618
        }
    }
}
